### PR TITLE
Drop support for legacy Python 2.7

### LINKED ISSUE #544: Drop Python 2 support
The upcoming fontTools 4.x branch will drop Python 2 support. We might want to use new features from it as we go, so drop Python 2?

This would prevent glyphsLib from being used in Glyphs, but I know of no one who actually does that.

### PR DESCRIPTION
**Pull request by madig**
Continuation from #550 because I can't push to hugovk's branch.

Closes #544.

There are more things that could be changed, like ,making the code in `types.ValueType` use f-strings, etc., but I feel that can also be done another time.

### CODE REVIEW

**Comment by madig** [comment]
@hugovk Can you please give the bot your ok?

**Comment by hugovk** [comment]
@googlebot I consent.

**Comment by madig** [comment]
Thanks!

**Comment by hugovk** [comment]
You're welcome!

**Pull request merged**
