### PR TITLE
Implement corner components

### PR DESCRIPTION
**Pull request by simoncozens**
Smart components were easy! Corner components... not so much. I don't quite understand how they work. But once I *do*, here's a framework for getting them implemented:

* Export them as hints (which we do already) in the UFO, ensuring we pass along the hint's name (since this is the name of the corner component glyph).
* Add a custom filter to "apply" those hints, by modifying the glyphs' path.
  * Convert the hints into a sensible data structure
  * ???
  * Profit!

### CODE REVIEW

**Comment by simoncozens** [comment]
This may turn out to be useful information: https://help.fontlab.com/fontlab/8/whats-new/whats-new-05-build-assemble/#skin-filter

**Comment by simoncozens** [comment]
It's done, ship it!

Screenshot 2022-11-18 at 06 42 23

**Comment by simoncozens** [comment]
I think I have done as much on this as my sanity can manage for now. It seems to implement everything apart from the left/right anchors; there's a warning issued if these are present. The cubic splitting algorithm in fontTools is different to the one in Glyphs, so when the outstroke of a corner is a curve, this gives subtly different but visually comparable results.

**Comment by simoncozens** [comment]
Write-up of algorithm: https://github.com/unified-font-object/ufo-spec/issues/213

**Comment by bramstein** [comment]
I would love to see this merged. Anything I/The Type Founders can do to help ship this feature?

**Comment by anthrotype** [comment]
@simoncozens is this in a mergeable state do you reckon? I can't go too deeply in the logic because I am not familiar enough with these.

**Comment by anthrotype** [comment]
> mergeablew

(ofc, provided we fix the merge conflicts and lint CI job failing first)

**Comment by simoncozens** [comment]
Yep, as mentioned I've really done as much as I can with this. And it's better than what we have already (i.e. nothing)

**Comment by anthrotype** [comment]
thank you very much, Simon. Will you be able to fix the merge conflicts and lint job at some point this week so we can get this in the next release?

**Comment by anthrotype** [comment]
the regression tests failing are expected, right? Feel free to merge when ready, thanks

**Pull request merged**
