### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by roberto-arista**
To be honest, the `userLoc` issue might be solved upstream, but this was a quick fix I was able to use to run my code.

### CODE REVIEW

**Comment by anthrotype** [comment]
ciao Roberto!
i see this PR is based on Glyphs3-merge branch (which I haven't reviewed/used yet) but at first sight both these changes look suspicious to me.

> sometimes userLoc is a str

when exactly and why?

> switch from .disabled to .active

how can an attribute that was named "disabled" be renamed "active" while seemingly keeping the same semantics?

**Comment by roberto-arista** [comment]
`.disabled` seems to have been deprecated:
https://github.com/googlefonts/glyphsLib/blob/ea5d7eb9e0320541ca1ec71299f8bb8b76a6e7da/Lib/glyphsLib/classes.py#L4147-L4153

**Comment by roberto-arista** [comment]
I totally agree about the `userLoc` fix, I just wanted to raise the issue. Probably the data needs some validation when it's parsed. We are using this branch for a QA tool we're working on at Dinamo and while parsing some files I encountered some `userLoc` in string form. I'll try to reproduce it.

**Comment by schriftgestalt** [comment]
I fixed the exception.

**Comment by schriftgestalt** [comment]
But I had fixed the "disabled" > "active" API but forgot to push. So now there is a conflict ;(

**Comment by roberto-arista** [comment]
I can close the pull request if you fixed it on your branch, let me know how you prefer to proceed.

**Pull request merged**
