### PR TITLE
Fix commented class issue

### PR DESCRIPTION
**Pull request by simoncozens**
This adds a newline to before the closing bracket of a class definition. Why do we want to do this? Well, there's an obscure corner case I just hit today.

Glyphs allows comments in glyph classes like so:

Screenshot 2021-01-28 at 14 40 25

If the last entry in a glyph class is commented out, glyphsLib writes a UFO feature file like so:

```
@Test = [ A
# B ];
```

The closing bracket of the class is commented out, causing a syntax error.

This PR writes the feature as

```
@Test = [ A
# B
];
```

instead.

### CODE REVIEW

**Comment by simoncozens** [comment]
Bump @anthrotype. This just hit me again.

**Comment by anthrotype** [comment]
ouch. sorry I didn't see this PR. Next time you can also ping @madig or @belluzj

**Comment by anthrotype** [comment]
merged too quicky perhaps. Shouldn't we also add a newline after the opening bracket for consistency?

**Comment by simoncozens** [comment]
Autogenerated feature files as part of a build pipeline are “binary equivalent”.  I don’t care what they look like, so long as they work.

**Pull request merged**
