### PR TITLE
Glyphs 3 support

### PR DESCRIPTION
**Pull request by simoncozens**
This is very much a WIP; don't bother trying to use it yet, but you can have a look at what I'm doing and where I'm up so. So far it can read a Glyphs3 format file (but will probably fail to read Glyphs2 files now) but does not store all that boring information about "components" and "paths", like anyone actually cares about those things.

### CODE REVIEW

**Review by schriftgestalt — COMMENTED** [review]
I renamed name > tag to not confuse it with stylistic set names.

**Review by schriftgestalt — COMMENTED** [review]
Renamed those to keep them together with default key sorting.

**Comment by simoncozens** [comment]
This is a silly approach and I’ve thought of another one which is a whole lot cleaner. I plan to decouple the marshalling (GS* object to/from dict-like structure) from the serialisation (reading/writing different styles of plist). Classes will then have access to the whole dict and get greater flexibility about what they do with members.

Also we can make decisions while marshalling about whether to emit Glyphs2-style or Glyphs3-style data structures (eg whether to put paths and components in their own slots or in a common shapes slot). And having the serialisation step separate means we can plug in the openstep-plist library for glyphs 3 and keep the current parser/writer for Glyphs 2.

Yeah. That’s clearly the way to go.

Keeping this open for now but will close when I have made a bit more progress and have something to show for it.

**Comment by anthrotype** [comment]
> decouple the marshalling (GS* object to/from dict-like structure) from the serialisation (reading/writing different styles of plist)

that was the original design, and what I also was proposing to back to when I made the openstep-plist parser

**Comment by simoncozens** [comment]
-> #651

**Pull request closed without merging**
