### PR TITLE
check that vert{Width,Origin} are not None, can be 0

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/googlefonts/glyphsLib/issues/557#issuecomment-768020307

### CODE REVIEW

**Comment by anthrotype** [comment]
I'm honestly not sure if this is the right fix. If anybody knows more, please chime in and comment /cc @m4rc1e @punchcutter

**Comment by m4rc1e** [comment]
I will take a look later today.

**Comment by punchcutter** [comment]
Georg told me once "If the manual set value is the same as the presumed default, it is omitted." So if it's 0 and Glyphs thinks it should be 0 then it won't explicitly add it. 
But if it's in the feature file or set in the Glyphs file it should be set so I think this looks good.

**Comment by m4rc1e** [comment]
Alright, I've just taken a look at @kokiabe's glyphs file and genned some fonts. Here's a 3 way diff.


Screenshot 2021-01-27 at 11 14 51

**Left: GlyphsApp | Center: This PR | Right: Current glyphsLib implementation**

This PR fixes the issue. Thanks Cosimo!

**Comment by m4rc1e** [comment]
I'll inspect what happens when we convert from ufo to glyphs after lunch. I have a hunch it may need a tweak as well.

**Comment by m4rc1e** [comment]
If I modify `builder.glyph.to_glyphs_glyph_height_and_vertical_origin` (ufo -> glyphs procedure) so zero values for height and origin are also accepted, we get several failing tests.

They're failing because defcon will initialise a new glyph so its height attribute will have a value of 0, https://github.com/robotools/defcon/blob/master/Lib/defcon/objects/glyph.py#L122 e.g

```
>>> import defcon
>>> f = defcon.Font()
>>> g = f.newGlyph("a")
>>> g.height
0
```

What's really strange is that if I have an existing glif file which doesn't specify a height attribute e.g

```
<?xml version='1.0' encoding='UTF-8'?>
<glyph name="a" format="2">
  <advance width="606"/>
  <unicode hex="0061"/>
  <anchor x="248" y="0" name="bottom"/>
  <anchor x="494" y="0" name="ogonek"/>
  <anchor x="358" y="522" name="top"/>
  <outline>
    <contour>
      <point x="91" y="-10"/>
      <point x="208" y="-10" type="curve" smooth="yes"/>
      <point x="279" y="-10"/>
      <point x="359" y="31"/>
      <point x="411" y="98" type="curve"/>
      <point x="405" y="71"/>
      <point x="402" y="53"/>
      <point x="402" y="41" type="curve" smooth="yes"/>
      <point x="402" y="15"/>
      <point x="422" y="-4"/>
      <point x="459" y="-4" type="curve" smooth="yes"/>
      <point x="468" y="-4"/>
      <point x="479" y="-2"/>
      <point x="494" y="0" type="curve"/>
      <point x="510" y="76" type="line"/>
      <point x="495" y="77"/>
      <point x="488" y="82"/>
      <point x="488" y="95" type="curve" smooth="yes"/>
      <point x="488" y="99"/>
      <point x="489" y="103"/>
      <point x="490" y="108" type="curve" smooth="yes"/>
      <point x="578" y="522" type="line"/>
      <point x="490" y="522" type="line"/>
      <point x="467" y="418" type="line"/>
      <point x="445" y="481"/>
      <point x="391" y="531"/>
      <point x="311" y="531" type="curve" smooth="yes"/>
      <point x="159" y="531"/>
      <point x="22" y="374"/>
      <point x="22" y="207" type="curve" smooth="yes"/>
      <point x="22" y="89"/>
    </contour>
  </outline>
</glyph>
```

and I load this glyph in defcon and type `glyph.width` it will return `0`. Surely attributes shouldn't be accessible if they haven't been declared? my knowledge of ufo/defcon is flakey at best so I do apologise if I'm jumping to conclusions/not understanding the implementation,

**Comment by m4rc1e** [comment]
> Surely attributes shouldn't be accessible if they haven't been declared? my knowledge of ufo/defcon is flakey at best so I do apologise if I'm jumping to conclusions/not understanding the implementation,

Looking at the ufo glif [spec](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#advance), it appears that the default for both height and width are `0`. However, it also says that height is optional if a width has been defined.

Since initing a new glyph or loading an existing glyph in Defcon will set the height attribute to 0, we can't use `if ufo_glyph.height is not None`. We can only use this if initing a new glyph doesn't add the height attribute by default. I could open an issue in defcon and propose we do this but it will probably break a boatload of test suites elsewhere etc.

Feel free to call out any assumptions I'm making. I'm no ufo expert.

**Comment by punchcutter** [comment]
I'm a little confused about this because vertOrigin and vertWidth are not part of the "glyph" or any part of a UFO glif file. They are separate values used to determine the `vmtx` settings. They aren't even stored in a UFO because there's nowhere to store them. I mean obviously there are places, but I just did a test saving a Glyphs file (with a bunch of these values explicitly set) as UFO and everything disappears. I suppose both Glyphs and then glyphsLib should be storing these values in the lib.plist or somewhere. Either way it's also entirely possible to have these values (the vmtx table) defined in the feature file instead. That's how our Adobe CJK fonts do it. We define the values there and makeotf compiles them.

**Comment by anthrotype** [comment]
yes, UFO default advance height is 0. It's not just defcon, it's the UFO spec.
https://github.com/unified-font-object/ufo-spec/issues/95#issuecomment-565425208

> vertOrigin and vertWidth are not part of the "glyph" or any part of a UFO glif file.

verticalOrigin is a lib key, whereas vertWidth corresponds to the `height` attribute of the `advance` element in the GLIF data structure.

**Comment by anthrotype** [comment]
I fear that we may not be able to fully roundtrip these back when going from Glyphs -> UFO, because of the differing default values in each.

**Comment by anthrotype** [comment]
(EDIT: in the previous message, I meant "from UFO -> Glyphs")

**Comment by anthrotype** [comment]
actually! I think we can make it work. Instead of checking "if ufo_glyph.height is not None: gs_glyph.vertWidth = ufo_glyph.height", we need to check `if ufo_glyph.height != ascender - descender:` which is the default value according to which Glyphs.app decides whether to store vertWidth in the .glyphs file or not.

**Comment by schriftgestalt** [comment]
Would that add a lot of `vertwidth = 0` if you convert a .ufo to .glyphs that wasn't exported from Glyphs?

It would help if the default in the ufo spec would be `None` instead of `0`. Is it even possible to export vertical spacing from a ufo? So it either export all zeros or omits nonspacing glyphs. What triggers the export of a `vmtx` table from the data in height field? If that value is not used to generate `vmtx`, we can ignore it and pick a lib key with a usable default?
I can add support for `vertOrigin/Width` lib keys in the ufo im/export in Glyphs.

**Comment by kokiabe** [comment]
Thanks everyone! When converting from `.glyphs` to `ttf`, the `fix-vert-zero branch` is working as I expected.
https://github.com/fontworks-fonts/Train/issues/1

**Comment by anthrotype** [comment]
> Would that add a lot of vertwidth = 0 if you convert a .ufo to .glyphs that wasn't exported from Glyphs?

Indeed, yes.. But I think that's the only way that we can make sure not to lose any data. Changing the default for glyph.height in the UFO speci is tricky since it'd be a breaking change.

> What triggers the export of a vmtx table from the data in height field?

in ufo2ft we check that these `openTypeVheaVert*` info attributes are set, and build vmtx/vhea/VORG accordingly
 https://github.com/googlefonts/ufo2ft/blob/74e1ee76555f09b24920d17c9afd26639b65270f/Lib/ufo2ft/outlineCompiler.py#L121-L130

**Comment by schriftgestalt** [comment]
But those zero values will make the .glyphs files totally unusable. 
The vertWidth is not always saved to .ufo. What is the criteria to omit it? Can the ufo code that reads the .ufo keep track if there was a explicit value in the file? That wouldn't break much.

**Comment by anthrotype** [comment]
> The vertWidth is not always saved to .ufo. What is the criteria to omit it? Can the ufo code that reads the .ufo keep track if there was a explicit value in the file? 

there's no vertWidth in UFO, there's glyph.height. It defaults to 0, and when it's zero ufoLib omits it. If there isn't an explicit height set, the value is thus understood to be 0, we can't change this for the current UFO3 version.

**Comment by schriftgestalt** [comment]
But why should `glyph.height` default to 0. It would make much more sense to default to `None` (and making round-tripping possible).

**Pull request merged**
