### PR TITLE
Handle features.fea code where a mark class is used as a glyph class

### PR DESCRIPTION
**Pull request by nrsiward**
see issue googlefonts/glyphsLib#694

### CODE REVIEW

**Comment by DavidRaymond** [comment]
What is the status of this?  It would be great to have this PR merged.

**Comment by anthrotype** [comment]
thanks for the PR.

> Is anything now preventing the merge?

the whole block of code feels a bit hackish, with all the FIXME and the all-catching AttributeErrors. I know you simply tried to fix your particular issue by adapting to the style of the neighbouring lines.

Also there's no accompanying tests to cover the newly added lines.

**Comment by anthrotype** [comment]
@nrsiward i'm OK to merge if you can add a small test for this in https://github.com/googlefonts/glyphsLib/blob/main/tests/builder/features_test.py

**Comment by anthrotype** [comment]
I will add the test, thanks

**Pull request merged**
