### PR TITLE
Compute clipBoxes for COLRv1 glyphs

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/googlefonts/glyphsLib/issues/847

I want to add tests before I remove the "WIP" but I file the PR to confirm the logic is sound

### CODE REVIEW

**Comment by anthrotype** [comment]
I had to also modify the `GSComponent.layer` property (which in the Glyphs Python Scripting API docs seems to be called differently as "[componentLayer](https://docu.glyphsapp.com/#GSComponent.componentLayer)" by the way..) and I am not 100% sure about this change, would love to get some confirmation as to the expected behavior.

Basically in order to compute the bounding box for a layer that contains components, I need to dereference these components to the corresponding layer in another glyph that these point to. The current code simply takes the component's base glyph and gets a layer with the same layerId as the component's parent layer, but I think this only works as intended for master layers. It surely did not work for me when I was using it with color layers.

For these, from my experiments within Glyphs.app, it appears that the layer that a component inside a color layer actually is pointing to is the _first_ color layer in the pointed-to glyph if any, otherwise the associated master layer.

Can anybody please confirm this?

/cc @schriftgestalt @khaledhosny @simoncozens

**Comment by schriftgestalt** [comment]
`component.layer` is the layer the component is in. Could have been called "container" or "parent". 

`component.compnentLayer` is the matching layer of the glyphs the component points to. Mostly that will do: `component.compoent.layers[component.layer.layerId]`But it will interpolate a new layer when the comment is in a brace layer of when it is a smart component. 

> For these, from my experiments within Glyphs.app, it appears that the layer that a component inside a color layer actually is pointing to is the first color layer in the pointed-to glyph if any, otherwise the associated master layer.

Yes. It tries to find a matching layer and otherwise falls back to the default layer.

**Comment by anthrotype** [comment]
> component.layer is the layer the component is in

oh, that's not how component.layer is implemented in glyphsLib currently.. There is already a component.parent that points to the GSLayer that component is in.

> Mostly

the devil is in the detail and I need to know _exactly_ rather than "mostly"

> a matching layer

matching in what sense?

**Comment by anthrotype** [comment]
> There is already a component.parent that points to the GSLayer that component is in.

looks like GSComponent.layer and GSComponent.parent are aliases and mean the same thing:

```python
l = Glyphs.font.selectedLayers[0]
assert l.components[0].parent is l.components[0].layer
```

**Comment by schriftgestalt** [comment]
The `.layer` and `.parent` is the same in most cases, only for GSNode it is different (`.parent` is a path).

**Comment by schriftgestalt** [comment]
>> Mostly

> the devil is in the detail and I need to know exactly rather than "mostly"

As I said. doing the interpolations for brace layers and smart components.

>> a matching layer

>matching in what sense?

When the component is in a "Color 1" or "[300<wg]" layer and the glyph has a matching layer. It uses a `layer.layerKey` (that is basically what you see in the layer panel) and `glyph.layerForKey_masterId_()`

**Comment by anthrotype** [comment]
hm what's a "layerKey"?

**Comment by anthrotype** [comment]
> layerKey is what you see in the layer panel

I see.. looks like it's a string that depends from the layer.attributes that are set, which define what kind of layer it is. glyphsLib doesn't currently implement that.

**Comment by anthrotype** [comment]
I added the functionality to fonttools directly (https://github.com/fonttools/fonttools/pull/3027), so I will no longer implement this in glyphsLib. I'll make ufo2ft call the fonttools' computeClipBoxes when building static COLR font and caller (in this case fontmake from glyphsLib-generated sources) does not provide pre-computed clipBoxes.

**Pull request closed without merging**
