### PR TITLE
apply master custom params _after_ writing master UFO features

### PR DESCRIPTION
**Pull request by anthrotype**
... otherwise, the 'Replace Feature' custom parameter will not work for masters, as it finds the features.fea text empty.

Similar to https://github.com/googlefonts/glyphsLib/pull/571 but rebased off latest master.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Isn’t this the same as https://github.com/googlefonts/glyphsLib/pull/571?

**Comment by moyogo** [comment]
> Isn’t this the same as #571?

It is but rebased and better :-)

@cosimo do you want tests?

**Comment by anthrotype** [comment]
Yes, in fact I linked to it in my previous comment. The difference is that this PR is based on updated master branch, thus takes into account the need to update GDEF after bracket glyphs are generated (https://github.com/googlefonts/glyphsLib/issues/578)

**Comment by anthrotype** [comment]
@moyogo thanks Denis, if you do have some tests, feel free to push here or pass them along

**Comment by khaledhosny** [comment]
I need to learn how to read.

**Comment by madig** [comment]
@moyogo do you happen to have a test lying around?

**Comment by punchcutter** [comment]
Any chance to get this in one of these days? One Noto update I've been sitting on absolutely requires this for the variable font and testing with this branch it all works as expected.

**Pull request merged**
